[workspace]
members = [
    ".",
    "crates/controller",
    "crates/device"
]

[package]
name = "woofer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.0"
serde = { version = "1.0.197", features = ["derive"] }
